#!/usr/bin/env python3
"""Generate src/width_table.zig from the Unicode Character Database.

A terminal draws some characters two columns wide and some not at all, and the
picker has to agree with it or every row after one of them lands in the wrong
column. The rules come from the UCD rather than from a hand-kept list, so a new
Unicode version is a rerun rather than an audit.

Run it with the version to pin to:

    zig build width -- 17.0.0
"""

import sys
import urllib.request

BASE = "https://www.unicode.org/Public/{version}/ucd/{path}"
OUT = "src/width_table.zig"

# Hangul Jamo medial vowels and final consonants compose onto the leading
# consonant before them, so they occupy no column of their own. They carry no
# property that says so, which is why every wcwidth spells them out like this.
HANGUL_CONJOINING = (0x1160, 0x11FF)


def fetch(version, path):
    with urllib.request.urlopen(BASE.format(version=version, path=path)) as r:
        return r.read().decode("utf-8")


def rows(text):
    """Yields (first, last, fields) for every data line, comments dropped."""
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        code = fields[0]
        if ".." in code:
            first, last = code.split("..")
        else:
            first = last = code
        yield int(first, 16), int(last, 16), fields[1:]


def codes_where(text, keep):
    """Every codepoint whose data line satisfies `keep`."""
    out = set()
    for first, last, fields in rows(text):
        if keep(fields):
            out.update(range(first, last + 1))
    return out


def to_ranges(codes):
    """Coalesces a set of codepoints into sorted, inclusive ranges."""
    ranges = []
    for code in sorted(codes):
        if ranges and code == ranges[-1][1] + 1:
            ranges[-1][1] = code
        else:
            ranges.append([code, code])
    return ranges


def emit(name, doc, ranges, out):
    out.append(f"/// {doc}")
    out.append(f"pub const {name} = [_]Range{{")
    for first, last in ranges:
        out.append(f"    .{{ .first = 0x{first:04x}, .last = 0x{last:04x} }},")
    out.append("};")
    out.append("")


def main():
    version = sys.argv[1] if len(sys.argv) > 1 else "17.0.0"

    eaw = fetch(version, "EastAsianWidth.txt")
    core = fetch(version, "DerivedCoreProperties.txt")
    category = fetch(version, "extracted/DerivedGeneralCategory.txt")
    emoji = fetch(version, "emoji/emoji-data.txt")

    # Two columns: the East Asian wide and fullwidth forms, plus everything that
    # defaults to an emoji presentation rather than a text one.
    wide = codes_where(eaw, lambda f: f[0] in ("W", "F"))
    wide |= codes_where(emoji, lambda f: f[0] == "Emoji_Presentation")

    # No column: marks that stack onto the character before them, and the
    # codepoints meant to have no visible rendering at all.
    zero = codes_where(category, lambda f: f[0] in ("Mn", "Me"))
    zero |= codes_where(core, lambda f: f[0] == "Default_Ignorable_Code_Point")
    zero |= set(range(HANGUL_CONJOINING[0], HANGUL_CONJOINING[1] + 1))

    # A codepoint cannot be both. Nothing visible enough to take two columns can
    # also take none, so the zero rule wins and the overlap is dropped.
    wide -= zero

    out = [
        f"//! Character widths derived from the Unicode Character Database {version}.",
        "//!",
        "//! Generated by `tools/gen-width.py`. Do not edit.",
        "",
        f'pub const unicode_version = "{version}";',
        "",
        "/// An inclusive range of codepoints sharing one width.",
        "pub const Range = struct { first: u21, last: u21 };",
        "",
    ]
    emit("wide", "Codepoints a terminal draws two columns wide.", to_ranges(wide), out)
    emit("zero", "Codepoints that occupy no column of their own.", to_ranges(zero), out)

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"wrote {OUT}: {len(to_ranges(wide))} wide ranges, {len(to_ranges(zero))} zero ranges")


main()
